{{- if eq .Values.global.componentsEnable.kubeworkz "true" }}
apiVersion: v1
kind: Service
metadata:
  name: kubeworkz
  namespace: {{ template "kubeworkz.namespace" . }}
spec:
  selector:
    kubeworkz.io/app: kubeworkz
  ports:
    - name: http
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: https
      protocol: TCP
      port: 7443
      targetPort: 7443
    - name: webhook
      port: 9443
      targetPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: kubeworkz-nodeport
  namespace: {{ template "kubeworkz.namespace" . }}
spec:
  type: NodePort
  selector:
    kubeworkz.io/app: kubeworkz
  ports:
    - name: http
      port: 7777
      targetPort: 7777
      nodePort: 30007
    - name: https
      port: 7443
      targetPort: 7443
      nodePort: 30443
---
{{- end }}