{{- if eq .Values.global.componentsEnable.webconsole "true" }}
apiVersion: v1
kind: Service
metadata:
  name: webconsole
  namespace: {{ template "kubeworkz.namespace" . }}
spec:
  type: ClusterIP
  selector:
    kubeworkz.io/app: kubeworkz-webconsole
  ports:
    - name: http
      port: 9081
      targetPort: 9081
---
{{- end }}