{{- if eq .Values.global.certs.mode "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: cube-tls-secret
  namespace: {{ template "kubeworkz.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.certs.tls.crt }}
  tls.key: {{ .Values.global.certs.tls.key }}
  ca.crt: {{ .Values.global.certs.ca.crt }}
  ca.key: {{ .Values.global.certs.ca.key }}
{{- end }}